package pro.aduki.crypto.dpop

import java.math.BigInteger
import java.security.KeyPairGenerator
import java.security.MessageDigest
import java.security.PrivateKey
import java.security.Signature
import java.security.interfaces.ECPublicKey
import java.security.spec.ECGenParameterSpec
import java.util.Base64

/**
 * Key is a device key for DPoP proofs (RFC 9449, ADK-AUTH-001 §9). It signs
 * and shows its public JWK; the private part is never readable, so a
 * hardware-backed implementation (Android Keystore, Secure Enclave) fits the
 * same interface. Hardware keys are P-256 (`ES256`); `EdDSA` is for software
 * keys only.
 */
interface Key {
    /** The JWS algorithm: `ES256` or `EdDSA`. */
    val alg: String

    /** The public JWK members, e.g. `kty`, `crv`, `x`, `y`. Never contains `d`. */
    val jwk: Map<String, String>

    /** Signs [input] and returns the raw JWS signature (ES256: 64 bytes r||s). */
    fun sign(input: ByteArray): ByteArray

    /** The RFC 7638 thumbprint (base64url SHA-256) the server stores as `jkt`. */
    fun thumbprint(): String {
        val members = when (jwk["kty"]) {
            "EC" -> listOf("crv", "kty", "x", "y")
            else -> listOf("crv", "kty", "x")
        }
        val canonical = members.joinToString(",", "{", "}") { "\"$it\":\"${jwk.getValue(it)}\"" }
        return Software.b64(MessageDigest.getInstance("SHA-256").digest(canonical.toByteArray()))
    }
}

/** A key held in process memory, generated by the JDK. Not hardware backed. */
class Software private constructor(
    override val alg: String,
    override val jwk: Map<String, String>,
    private val private: PrivateKey
) : Key {

    override fun sign(input: ByteArray): ByteArray {
        val signature = Signature.getInstance(if (alg == "ES256") "SHA256withECDSAinP1363Format" else "Ed25519")
        signature.initSign(private)
        signature.update(input)
        return signature.sign()
    }

    override fun toString() = "Software($alg)" // never prints key material

    companion object {
        fun b64(bytes: ByteArray): String = Base64.getUrlEncoder().withoutPadding().encodeToString(bytes)

        /** A fresh P-256 key (`ES256`), the algorithm hardware stores share. */
        fun p256(): Software {
            val pair = KeyPairGenerator.getInstance("EC").apply { initialize(ECGenParameterSpec("secp256r1")) }.generateKeyPair()
            val point = (pair.public as ECPublicKey).w
            return Software(
                "ES256",
                mapOf("kty" to "EC", "crv" to "P-256", "x" to b64(fixed(point.affineX)), "y" to b64(fixed(point.affineY))),
                pair.private
            )
        }

        /** A fresh Ed25519 key (`EdDSA`), for software-only clients. */
        fun ed25519(): Software {
            val pair = KeyPairGenerator.getInstance("Ed25519").generateKeyPair()
            val raw = pair.public.encoded.takeLast(32).toByteArray() // X.509 prefix + 32-byte key
            return Software("EdDSA", mapOf("kty" to "OKP", "crv" to "Ed25519", "x" to b64(raw)), pair.private)
        }

        private fun fixed(value: BigInteger): ByteArray {
            val raw = value.toByteArray().dropWhile { it == 0.toByte() }.toByteArray()
            return ByteArray(32 - raw.size) + raw
        }
    }
}
