[book]
title = "Aduki Kotlin SDK"
authors = ["Aduki Labs"]
description = "Developer guide and API reference for the Aduki Kotlin SDK."
language = "en"
src = "."

[output.html]
git-repository-url = "https://github.com/adukilabs/aduki-kt"
edit-url-template = "https://github.com/adukilabs/aduki-kt/edit/main/docs/{path}"
site-url = "/kt/"
default-theme = "rust"
preferred-dark-theme = "coal"

[output.html.fold]
enable = true
level = 1
